project:
  type: website

      
website:
  title: "Chronic diseases data science project"
  navbar: 
    search: true
    collapse-below: xxl
    left:
      - href: about.qmd
        text: about Michael
        
      - href: Code.qmd
        text: Code
        
      - href: Data.qmd
        text: Data
        
      - href: Introduction.qmd
        text: Introduction
        
      - href: Data_Gathering.qmd
        text: Data Gathering
        
      - href: Data_Cleaning.qmd
        text: Data Cleaning
        
      - href: eda.qmd
        text: Data Exploration
        
      - href: Na誰ve_Bayes_R.qmd
        text: Na誰ve Bayes in R

      - href: Na誰ve_Bayes_python.qmd
        text: Na誰ve Bayes in Python
  
      - href: Clustering_R.qmd
        text: Clustering in R

      - href: Clustering_Python.qmd
        text: Clustering in Python
        
      - href: Dimensionality_reduction_R.qmd
        text: Dimensionality reduction in R

      - href: Dimensionality_reduction_python.qmd
        text: Dimensionality reduction in Python
       
      - href: Decision_Trees.qmd
        text: Decision Tress
        
      - href: ARM.qmd
        text: ARM
        
      - href: Conclusions.qmd
        text: Conclusions
     


format:
  html:
    theme: 
      - Lux
      - custom.scss
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: false
    code-fold: true
    code-copy: true
    code-tools: true
    code-overflow: wrap

editor: visual





