project:
  type: website

      
website:
  title: "Predictive data modelling with chronic diseases."
  navbar: 
    search: true
    collapse-below: xxl
    left:
      - href: about.qmd
        text: about Michael
        
      - href: Code.qmd
        text: Code
        
      - href: Data.qmd
        text: Data
        
      - href: Naïve_Bayes.qmd
        text: Naïve_Bayes
        
      - href: Introduction.qmd
        text: Introduction
        
      - href: Data_Gathering.qmd
        text: Data Gathering
        
      - href: Data_Cleaning.qmd
        text: Data Cleaning
        
      - href: eda/eda.qmd
        text: Data Exploration
        
      - href: Clustering_R.qmd
        text: Clustering in R

      - href: Clustering_Python.qmd
        text: Clustering in Python
        
      - href: Dimensionality_reduction_R.qmd
        text: Dimensionality reduction in R

      - href: Dimensionality_reduction_python.qmd
        text: Dimensionality reduction in Python
       
      - href: Decision_Trees.qmd
        text: Decision Tress
        
      - href: ARM.qmd
        text: ARM
        
      - href: Conclusions.qmd
        text: Conclusions
     


format:
  html:
    theme: journal
    #css: journal.scss
    toc: true

editor: visual




