---
title: "About Michael"
---

-    Hello , my name is Xinzhe Xie, I prefer to go by Michael. I come from Chongqing, China. I graduated from the University of Massachusetts Amherst in 2021 as a Statistics and Actuary major, after I graduated, I worked in China as a data analyst, working on developing river water quality forecast models. My work primarily focuses on using mechanical modeling methods using R, building interactive data visualization using R shiny, deploying applications using shiny proxy and docker, neural networking, and SARIMA time series were also implemented. I'm interested in machine learning and time series modeling, I would love to become a data scientist after graduating from the program, especially in environmental and healthcare fields. As for hobbies, I'm really passionate about weightlifting, specially weighted calisthenics and power lifting. I'm also a swimming athlete growing up. 

-    My definition of data science is that in my understanding, I'd say that data science is the field that combines computer science and Statistics, like computational physics or computational mathematics, data science is more like "computational statistics" but focuses more on practical fields in industries where data scientist can implement the knowledge of statistical method with the aid of computer programing to make prediction models, machine learning models, and etc. Gaining insights from models in order to better understanding the data.

-   I'm really passionate about time series and machine learning, since I had lots of experience with time series during my work before coming to Georgetown where I had to deal with large times series data sets, applying different models to the data to better understand the trend, and that is the reason why I signed up for DSAN 5600 this semester. Also, I'm passionate with machine learning, especially deep learning method including neutral network modeling, also those methods can be applied to time series which definitely improves the overall accuracy of modelling.

-   The major difference between a technical report and data science report is their targeted audience, an academic paper is for peers reviewing, that requires prior understanding of the subject whereas a data science report is for everyone interested in the topic, because data is everywhere, the data science style report has to be simple to understand, the visualization needs to pleasant and human readable.  The reason why visual data storytelling is so important is that we are trying to explain complex things to non-experts, we need to simplify things so that people can understand and also enjoy what we're talking about. 
